from .allen_srl_extraction_task import AllenSRLExtraction
from .coreference_resolution_task import CoreferenceResolution
from .discourse_simplifcation_task import DiscourseSimplificationTask
from .sentence_splitting_task import SentenceSplitTask
from .uncertainity_extraction_task import UncertainityExtractionTask
